---
title: "Bayesian deconvolution of delayed incidence"
output: html_notebook
---

## Preamble

```{r}
library(ggplot2)
library(dplyr)
library(rstan)
source('../../R/util.R')
```


## Create an incidence curve

It's a Gaussian, naturally:

```{r}
sim_df <- {
  a <- seq(-4, 4, length.out = 30)
  x <- dnorm(a) * 10000
  
  data.frame(t = 1:length(x), x = round(x))
}

ggplot(sim_df, aes(x = t, y = x)) +
  geom_col()
```

## Make a delay distribution from a discretized gamma

```{r}
delay_dist <- {
  t <- seq(0, 39)
  p_unnorm <- pgamma(t + 1, shape = 2.5, rate = 0.25) - pgamma(t, shape = 2.5, rate = 0.25)
  
  data.frame(t = t, pmf = p_unnorm / sum(p_unnorm))
}

ggplot(delay_dist, aes(x = t, y = pmf)) +
  geom_col()
  
```

## Delay incidence curve

```{r}
obs_df <- {
  y <- convolve_delay(sim_df$x, delay_dist$pmf)
  t_start <- sim_df$t[1]
  t_end <- sim_df$t[nrow(sim_df)] + nrow(delay_dist) - 1
  data.frame(t = t_start:t_end, y = round(y))
}

ggplot(obs_df, aes(x = t, y = y)) +
  geom_col()
```

## Deconvolve

```{r}
model <- stan_model('../../stan/deconvolve-uncorrelated.stan')
```

```{r}
model_input_data <- list(
  delay_min = min(delay_dist$t),
  n_delay = length(delay_dist$pmf),
  pmf_delay = delay_dist$pmf,
  t_obs_min = obs_df$t[1],
  n_obs = nrow(obs_df),
  y_obs = obs_df$y,
  t_unobs_min = sim_df$t[1],
  n_unobs = nrow(sim_df)
)
```


```{r}
fit <- sampling(model, model_input_data, chains = 1, cores = 1)
```

```{r}
params <- rstan::extract(fit)
```

```{r}
result_df <- sim_df %>%
  mutate(
    xhat_mean = colMeans(params$x_unobs),
    xhat_025 = apply(params$x_unobs, 2, function(x) quantile(x, 0.025)),
    xhat_975 = apply(params$x_unobs, 2, function(x) quantile(x, 0.975))
  )

ggplot(result_df) +
  geom_ribbon(aes(x = t, ymin = xhat_025, ymax = xhat_975), fill = 'lightgray') +
  geom_line(aes(x = t, y = x)) +
  geom_line(aes(x = t, y = xhat_mean), color = 'red') +
  geom_line(data = obs_df, mapping = aes(x = t, y = y), lty = 2)
```
